apiVersion: apps/v1
kind: Deployment
metadata:
  name: sun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sun
  template:
    metadata:
      labels:
        app: sun
    spec:
      containers:
      - image: okteto.dev/sun:latest
        name: sun
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e91b1edf-0c6d-4965-b603-f00a8d7130ba"
        - name: Vless_Path
          value: "/a73d9a21"
        - name: Vmess_UUID
          value: "e91b1edf-0c6d-4965-b603-f00a8d7130ba"
        - name: Vmess_Path
          value: "/7e3ff02f"
        - name: Share_Path
          value: "/v2link"
